guard 'sass', 
  :input => 'compile/sass', 
  :output => 'css',
  :load_paths => ['compile/sass/partials'],
  :style => :compressed
  
#watch these folders/files and reload browser when they are saved
guard 'livereload' do
  watch(%r{templates/+\.(php|html)}) #reload html templates on save
  watch(%r{css/.+\.css})
  watch(%r{js/.+\.js})
end

#use juicer to merge files referenced in js and create a minified js file
#juicer wiki https://github.com/cjohansen/juicer/wiki/Usage
guard 'process', :name => 'Minify Main JS', :command => 'juicer merge compile/js/main.js -o js/main.js --force -i -s' do
  watch(%r{compile/js/main\.js})
end
guard 'process', :name => 'Minify Foundation JS', :command => 'juicer merge compile/js/foundation.js -o js/foundation.js --force -i -s' do
  watch(%r{compile/js/foundation\.js})
end