guard 'sass', 
  :input => 'compile/sass', 
  :output => 'css',
  :load_paths => ['compile/sass/partials'],
  :style => :compressed
  
#watch these folders/files and reload browser when they are saved
guard 'livereload' do
  watch(%r{templates/+\.(php|html)}) #reload html templates on save
  watch(%r{css/.+\.css})
  watch(%r{js/.+\.js})
end

guard 'process', :name => 'minify-js', :command => 'juicer merge compile/js//main.js --force -o js/main.js -s' do
  watch %r{compile/js/main\.js}
end